### ISSUE TITLE
Account for non-steady-state outliers from FMRIPREP in confound regression

### ISSUE THREAD

**Issue by utooley** [PennBBL/xcpEngine#151]
FMRIPREP outputs in the confound regressors .tsv the number of detected non-steady state outliers (or dummy scans, if so) at the beginning of each scan. You could feed these in by hand through `confound2_custom` for each subject, but it would take some finagling to pull the columns and name them as xcpEngine expects. It would be really handy to be able to just set an option to pull those columns and use them (or not, as desired).

I couldn't find a place in xcpEngine to discard a number of volumes from the beginning of the timeseries, other than using the `confound2_custom` option.

**Comment by a3sha2** [comment]
this is good idea for  for custom regressors. 
There are many options. We can include the header of  the prefer  desired columns in design file. this will be fine if it is similar for all subjects. 
However, custom regressors usually required preprocessing by the users because the length of the regressors must  equal to number volume of bold signals. For instance, respiration signals may not have equal length as number of bold volume, it will required the user to address this before running xcp, usually by interpolation or matching.   
It is something we can do though, we can discuss about this more. 

on discarding the volume 
Discarding the volume (in xcp) will make the number of volume not equal to original regressors length. The `regress` module will exit/stop if the number of volume is not equal to length of  regressors. Though we can make it work by delete the corresponding regressors time point. The feature is the in prestats (DVO). 
The second thing is that, xcp uses `fd` and all `*dvars` from frmiprep regressors. These parameters are derived from other regressors. Discarding the volumes in xcp require to recompute `fd` and  `*dvars` again in xcp. Best option is to delete the volume during `fmriprep` if the option is available. 
We can discuss this more to see how we can implement it.

**Comment by utooley** [comment]
So I'm finally coming back around to this--I understand how to put the header in the cohort and design file and use `confound2_custom[2]= ${dummy_tr[sub]}` to pull an individualized regressor for each subject (will it fail if there's no regressor there? Or do I need a fake regressor of all 0's for folks with no non-steady state outliers?). 

However, fmriprep outputs each dummy TR regressor as a separate column in the `confounds_regressors.tsv` file. My impression is that I have to write a script to, for each subject, pull however many of those columns there are and save them separately as `.1D` files in their subject directory. Then, each file needs its own column in the cohort file as a custom regressor, with the filename pointing to that `1D` file. However, I'm stuck on how that works if there are varying numbers of custom regressors per subject. Can I write `confound2_custom[2]= ${dummy_tr1[sub]},${dummy_tr2[sub]},${dummy_tr3[sub]}` for all the possible numbers of regressor columns in the cohort file, and only those that exist will be pulled? Am I missing something obvious, and each vol doesn't need its own dummy regressor `1D` file? Or will this work?

**Comment by mwvoss** [comment]
Hello, we are also trying to determine the best way to account for dummy volumes in our nuisance regression via xcp. I understand we can delete the volumes, but wondered if there's a way to account for them in the regression before going to deletion.

We have tried using the custom regressor option like shown above, with a fixed file with one column composed of 1's for dummy vols and 0's for all other volumes, specified for example as:
`confound2_custom[2]=/Shared/vosslabhpc/Projects/BETTER/3-Experiment/2-data/bids/derivatives/code/xcp/dummy_vol_regressor.1D`

However, this file doesn't seem to be incorporated into the nuisance regression. I attached an example subject's design file and their log. 
[fc_ariveradompenciel_202105121259_sub-GE120001_ses-pre_run-1LOG-process.txt](https://github.com/PennLINC/xcpEngine/files/6472568/fc_ariveradompenciel_202105121259_sub-GE120001_ses-pre_run-1LOG-process.txt)

We'd love feedback on the best approach to go about this, thanks.

@utooley @ariveradompenciel
