### ISSUE TITLE
Normalize to MNI via a different space (OASIS)

### ISSUE THREAD

**Issue by caugolm** [PennBBL/xcpEngine#235]
I'm hoping to process some pCASL data using the xcpEngine. I have already processed the T1 data using antsCorticalThickness with an OASIS template/template space and I have the OASIS to MNI warps. I was wondering if you could recommend a way to link up my already-processed structural data to use with the xcpEngine pCASL processing module.

**Comment by a3sha2** [comment]
Hi Chris, 
It will only be possible if you run antsCorticalThickness  using xcpengine. You would have just change the  `standard=MNI%2x2x2` to `standard=MNI%2x2x2 via OASIS%1x1x1`
In xcpengine, we rename the files to be uniform and esier to read for user, and compatible for other modules. 

We  added some features  with the meeting we had the other day. please see documentation  on how to add t1w to cohort file if you have not run struc or fmriprep  before. 
https://xcpengine.readthedocs.io/config/cohort.html#asl-processing 
it take about an hour due to  antsregistration (between  T1 and template)

**Comment by caugolm** [comment]
Hi Azeez, 
Thanks for your reply! I'll try running it that way. 
In the mean time, I've used antsApplyTransforms to combine my existing T1-to-OASIS and OASIS-to-MNI warps, and using that to move my data into MNI space. In addition, I've used a series of symlinks and simple calculations to get many of the images into the same directory structure and naming convention as xcpEngine/fmriprep. So far, it seems feasible that this could work to avoid re-processing the whole dataset, but an hour to get the T1-to-template warps is not bad at all.
Thanks,
Chris
