### ISSUE TITLE
How to do soft scrubbing (volume censoring using the GLM)?

### ISSUE THREAD

**Issue by egarza** [PennBBL/xcpEngine#408]
**Describe the bug**
XCPEngine gives the option to do either despike or volume censoring. However, despike is done with AFNI and it is not based on FD thresholds, while volume censoring is hard scrubbing (removal of volumes).

In order to only add the censored volumes to the GLM and do soft scrubbing, is there a command for that or should the regressors be added to `confound2_custom`.

**Additional context**

**Comment by egarza** [comment]
Checking the tutorial better, I think you call soft-scrubbing as `spike regression` and hard-scrubbing as `volume censoring`. With that in mind, how can we do `spike regression` only? 

For example, on the design file, do we only do `confound2_censor[2]=0` and `confound2_framewise[2]=fds:0.25,dv:2`? Or how to only do spike regression?

Thank you,

Eduardo

**Comment by a3sha2** [comment]
thank you @egarza 
the despiking is done by AFNI's 3dDespike and not based on FD thresholds. this is done by adding DSP to the regression steps  `regress_process[3]=DMT-DSP-TMP-REG`

For the censoring, censoring are done by flagging volume with parameters(fd and dv) greater than the threshold. `confound2_framewise[2]=fds:0.25,dv:2`.  and  confound2_censor[2]=1 for spike regression. 

Scrubbing also includes masking out the non-contiguous segments of data between outliers. The number of contiguous volumes required to survive masking is set flexibly by censor_contig[2]=X, where X is the minimum number of contiguous threshold-surviving time points required for those time points to survive masking.  

if you identify volume with spike rather than using threshold, you can add it with `confound2_custom[2]`.  It is tricky because you have to create a matrix. for instance if bold has total 10 volumes and volume 4 and 6 are flagged, the matrix will be 10 rows by 2 volumes flagged and volume 4 and 6 are labeled 1s in the  column separately ::  
```
0 0
0 0
0 0
1 0
0 0
0 1
0 0
0 0
0 0
0 0
```

**Comment by egarza** [comment]
Hi Azeez,

Thanks for the quick answer. But what if I want the flagging of volumes with FD and DV, but I do not want the volume to be removed, I only want the volume to be regressed as a confound? Because right now my subjects end up with less volumes. Thank you

Eduardo

**Comment by a3sha2** [comment]
yes, there is full residualized  data in the regress folder `regress/*_uncensored.nii.gz`

**Comment by egarza** [comment]
I think we have a good idea of it, thank you
