### ISSUE TITLE
NaN values for the regional ALFF and ReHo outputs

### ISSUE THREAD

**Issue by llevitis** [PennBBL/xcpEngine#418]
Hi! Sorry for posting another question here; I just wanted to confirm that it's expected for some regions to have NaN values for ReHo and ALFF. It's my first time working with these metrics, and I was wondering if it would be acceptable to set those values to be 0 for subsequent analyses. Thank you!

**Comment by llevitis** [comment]
@a3sha2 I'd appreciate your guidance with this :)

**Comment by a3sha2** [comment]
I am sorry for late response @llevitis 
Please let me know which of the regions and/or atlas pls. 
is it outside brain?

**Comment by llevitis** [comment]
Hi @a3sha2 
here's an example using the Glasser parcellation where each row is a subject (I post-hoc merged the individual regional ReHo outputs myself)

![image](https://user-images.githubusercontent.com/17363738/101515598-8533e300-394c-11eb-99fb-5e65b9140bc8.png)

**Comment by a3sha2** [comment]
this is not expected. pls can you share the log file of one the subject with me pls

**Comment by llevitis** [comment]
[fc_levitise2_202012031421_sub-NDARINV8XENUGU9_ses-v01LOG-process.txt](https://github.com/PennBBL/xcpEngine/files/5660882/fc_levitise2_202012031421_sub-NDARINV8XENUGU9_ses-v01LOG-process.txt)

I added the '.txt' extension so that I could upload it here. Please let me know if you were referring to a different type of log file?

**Comment by llevitis** [comment]
hi @a3sha2 - was that the right file or do you need another one? Please let me know if there's any other info I could share :) Thanks again for your help!

**Comment by a3sha2** [comment]
Hi @llevitis  sorry for late response.
fmriprep functional output  in T1w or MNI space are always in native space resolution. There is likely that your bold space resolution is very big. The main issues is that, xcp always does  ROI extraction in bold input space which means that atlases (in MNI template space) are registered or resampled to bold input space. Then, Glasser atlas has many very small parcels and during registration to bold space, it is likely that some parcel disappeared due to big resolution of bold input space.  
I will be glad if  you can share one of  your data

**Comment by llevitis** [comment]
@a3sha2 Oh interesting... I ran this using the MNI space output from fMRIPrep. Would you recommend I do this in T1w space instead? What's your email?

**Comment by a3sha2** [comment]
Yes, if your output is in MNI space from fmriprep, the bold  still retain resolution of (original)native space (not resolution of MNI)
my email is azeez.adebimpe@outlook.com
