### ISSUE TITLE
Distortion correction module

### ISSUE THREAD

**Issue by biogeo** [PennBBL/xcpEngine#64]
I'm opening an issue to discuss the possibility of a new module for doing distortion correction. This will probably entail calling out to FSL's FUGUE command.

This enhancement will improve the initial processing pipeline for use in primate neuroimaging data, where magnetic field susceptibility artifacts are relatively large due to the small primate brain and large sinuses.

Once I've had a chance to work through it a bit and see how things go, I'll open a pull request with a new module (probably at least several weeks from now).

Thanks for the walkthrough of xcpEngine today, it was really helpful!

**Comment by adrose** [comment]
Hi @biogeo 

The possibility is certainly there, we currently have a dico module here: https://goo.gl/Jzt8uK

It is currently not very flexible and requires some bbl specific inputs. However I was anticipating expanding its flexibility (see here: https://github.com/PennBBL/xcpEngine/issues/9 ). 

Like I mentioned all we would really need to do to expand this is provide the module with the phase encoding direction assuming you have your rps and dico maps.

A lot ( i.e. All ) of the code doing the heavy lifting in our DICO procedure was developed by [Mark Elliot](https://www.med.upenn.edu/cmroi/mark-elliott.html), not that this should prevent us from working on this, just wanted to make it clear that most recognition for these tools should go to him. 

Essentially to process the PNC data, what we needed to perform the distortion correction were the Magintude map dicoms, Phase map dicoms, Extracted structural and non extracted structural images. With this we then made an rps map, and a dico map, which is what we provide the DICO module. Creating the rps and dico map was performed by one of Mark Elliots scripts 
```
/home/melliott/scripts/dico_b0calc_v3.sh
```

Assuming you can successfully create the distortion nifti images then we can modify the module to accept the run the fugue command quite easily.

Happy to talk more about this - I think it is a large bottle neck to a lot of studies so it certainly is a useful expansion, but it is also a large bottle neck because of the difficulty in performing this correctly.

Thanks,

Adon

**Comment by adrose** [comment]
Sorry @biogeo I did not make it clear at all that the path I link to in melliot's home exists on chead

**Comment by mattcieslak** [comment]
dico is done in fmriprep now
